hosts: [
  { host_ip: "10.100.98.202", host_name: "openshift"} 
]

obsolete_services:
  - puppet
  - chef-client

centos_files: [
     { src: "centos.sshd_config", dest: "/etc/ssh/sshd_config" },
  ]
